baseURL = "https://furniture.bangunan.co/"
languageCode = "id"
title = "Furniture Minimalis | Jual Furniture Minimalis Meja Rotan, Kursi Rotan"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jual Furniture Minimalis - Temukan furniture minimalis berkualitas, mulai dari meja rotan hingga kursi rotan cocok untuk mempercantik ruangan rumah Anda"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual meja rotan", "kursi rotan", "meja minimalis", "kursi minimalis", "furniture rotan", "custom meja rotan", "custom kursi rotan", "meja rotan murah"]
  base_price = 750000
  price_range = 300000
  free_shipping = true
  materials = [
  "Meja Rotan Minimalis",
  "Kursi Rotan Custom",
  "Meja Rotan Kombinasi Kayu",
  "Kursi Rotan Kombinasi Kayu",
  "Meja Rotan Outdoor",
  "Kursi Rotan Outdoor"
  ]
  categories = ["Meja Rotan", "Kursi Rotan", "Furniture Rotan", "Furniture Minimalis"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Penggantian atau pengembalian gratis untuk barang dengan cacat produksi.",
  "Barang yang tidak sesuai pesanan dapat dikembalikan tanpa biaya tambahan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Furniture Minimalis Berkualitas"
  hero_description = "Kami menawarkan berbagai pilihan furniture minimalis seperti meja rotan dan kursi rotan yang dirancang dengan estetika modern dan bahan berkualitas tinggi. Solusi ideal untuk menambah kenyamanan dan gaya di rumah atau kantor Anda."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Produk"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan produk furniture dengan desain minimalis, bahan berkualitas, harga terjangkau, dan gratis biaya pengiriman juga gratis konsultasi desain interior untuk membantu Anda menemukan solusi furniture yang tepat untuk ruang Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "Furniture.bangunan.co menawarkan berbagai produk furniture minimalis seperti meja rotan dan kursi rotan dengan desain modern dan bahan berkualitas. Kami mengutamakan kepuasan pelanggan dengan produk yang tahan lama, estetis, dan harga yang bersaing. Pilih kami untuk melengkapi rumah atau kantor Anda dengan furniture yang elegan dan fungsional."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Rudi|Hendra|Agus|Wawan|Fajar|Rio}"
  message = "{Saya membeli kursi rotan dari furniture.bangunan.co untuk rumah saya, dan hasilnya {sangat memuaskan|luar biasa}. Kualitas produk {sangat baik|terbaik} dan sesuai dengan {harapan|ekspektasi} saya.|Kursi rotan dari furniture.bangunan.co {berkualitas|hebat} dan hasilnya {sesuai|tepat} dengan yang saya inginkan.}"
  response = "{Terima kasih atas kepercayaannya! Kami senang dapat menyediakan produk yang {memuaskan|hebat} untuk rumah Anda.|Kami sangat menghargai kepercayaan Anda. Senang Anda puas dengan produk kami!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Fitri|Lina|Diah|Maya|Nur}"
  message = "{Furniture.bangunan.co {sangat membantu|memudahkan} dalam melengkapi dekorasi rumah saya. Desainnya {modern|minimalis} dan produk yang saya beli {sangat berkualitas|berkualitas tinggi}.|Saya {sangat terbantu|puas} dengan layanan dari furniture.bangunan.co. Produk yang saya beli {berkualitas|hebat} dan desainnya {modern|elegan}.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan furniture {minimalis|modern} dari kami.|Terima kasih atas ulasannya. Kami senang dapat membantu menciptakan dekorasi rumah Anda!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Galih|Rizal|Bambang|Faisal|Ali|Toni|Deni}"
  message = "{Produk meja rotan dari furniture.bangunan.co {sangat elegan|mewah} dan cocok untuk ruang tamu saya. Proses pembeliannya juga {sangat mudah|sederhana} dan {cepat|efisien}.|Meja rotan dari furniture.bangunan.co {cantik|elegan} dan sesuai dengan gaya ruang tamu saya. Pembeliannya {mudah|praktis} dan {cepat|aman}.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan furniture yang {tidak hanya fungsional|serba guna} tetapi juga {estetis|indah}.|Kami senang bisa menyediakan produk yang cocok untuk Anda. Terima kasih atas kepercayaannya!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Deni|Hendra|Toni|Wawan|Gilang|Ari|Benny|Yudi}"
  message = "{Saya {sangat puas|senang} dengan kursi dan meja rotan dari furniture.bangunan.co. Desainnya {minimalis|modern} dan kualitasnya {sangat memuaskan|hebat}.|Kursi dan meja rotan dari furniture.bangunan.co {berkualitas|bagus}, desainnya {minimalis|elegan}, dan kualitasnya {top|luar biasa}.}"
  response = "{Senang mendengar Anda puas dengan produk kami. Terima kasih atas kepercayaannya!|Kami sangat menghargai kepercayaan Anda. Terima kasih telah memilih produk kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan furniture.bangunan.co {sangat memuaskan|luar biasa}. Produk yang saya beli {berkualitas|terbaik} dan sesuai dengan {harapan|ekspektasi} saya.|Saya {puas|senang} dengan layanan dari furniture.bangunan.co. Produk yang saya beli {berkualitas tinggi|hebat} dan hasilnya {memuaskan|luar biasa}.}"
  response = "{Terima kasih! Kami senang dapat membantu mewujudkan suasana rumah yang {nyaman|indah} dengan produk {terbaik|hebat}.|Kami sangat menghargai ulasan Anda. Terima kasih atas kepercayaannya!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Rio|Galih|Faisal|Yanto|Benny|Toni|Deni|Rizal|Wawan}"
  message = "{Produk furniture minimalis dari furniture.bangunan.co {sangat sesuai|tepat} dengan desain interior rumah saya. Proses pengirimannya juga {cepat|aman|efisien} dan produknya {berkualitas|hebat}.|Saya {terkesan|puas} dengan layanan dari furniture.bangunan.co. Produk yang saya beli {berkualitas tinggi|hebat} dan pengirimannya {cepat|aman}.}"
  response = "{Kami senang mendengar bahwa Anda puas dengan produk dan layanan kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah mempercayakan desain interior rumah Anda kepada kami. Kami senang produk kami sesuai dengan harapan Anda.}"
  rating = 5

[[params.tabelItems]]
  name = "Meja Rotan Minimalis"
  price = "2.500.000 /unit"
[[params.tabelItems]]
  name = "Kursi Rotan Custom"
  price = "1.200.000 /unit"
[[params.tabelItems]]
  name = "Meja Rotan Kombinasi Kayu"
  price = "3.000.000 /unit"
[[params.tabelItems]]
  name = "Kursi Rotan Kombinasi Kayu"
  price = "1.500.000 /unit"
[[params.tabelItems]]
  name = "Meja Rotan Outdoor"
  price = "2.800.000 /unit"
[[params.tabelItems]]
  name = "Kursi Rotan Outdoor"
  price = "1.000.000 /unit"

[params.appliList]
  "Meja Rotan Minimalis" = "interior rumah, ruang kerja"
  "Kursi Rotan Custom" = "ruang tamu, ruang makan"
  "Meja Rotan Kombinasi Kayu" = "dapur, ruang makan"
  "Kursi Rotan Kombinasi Kayu" = "ruang makan, ruang tamu"
  "Meja Rotan Outdoor" = "teras, taman"
  "Kursi Rotan Outdoor" = "taman, area outdoor"

[params.kegunaanList]
  "Meja Rotan Minimalis" = "cocok untuk interior minimalis di rumah atau ruang kerja"
  "Kursi Rotan Custom" = "digunakan untuk ruang makan atau ruang tamu dengan desain minimalis"
  "Meja Rotan Kombinasi Kayu" = "cocok untuk ruang makan atau dapur dengan kesan modern"
  "Kursi Rotan Kombinasi Kayu" = "digunakan untuk melengkapi ruang makan atau ruang tamu"
  "Meja Rotan Outdoor" = "digunakan untuk area outdoor seperti teras atau taman"
  "Kursi Rotan Outdoor" = "cocok untuk taman atau ruang terbuka"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Furniture Minimalis Meja Rotan & Kursi Rotan | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"